name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }}
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        export PATH=$HOME/.roswell/bin:$PATH
        ros install rove
        rove ~/.roswell/local-projects/cxxxr/strict-function/strict-function.asd
